export {default as Ecommerce} from './Ecommerce'
export {default as Calendar} from './Calendar'
export {default as Kanban} from './Kanban'
export {default as Area} from './Charts/Area'
export {default as Bar} from './Charts/Bar'
export {default as Line} from './Charts/Line'
export {default as Pie} from './Charts/Pie'
export {default as Pyramid} from './Charts/Pyramid'
export {default as Stacked} from './Charts/Stacked'
export {default as Colorpicker} from './Colorpicker'
export { default as Editor } from './Editor'
export {default as Employees} from './Employees'
export {default as Customer} from './Customer'
export {default as Orders} from './Orders'
